/* RTC:
 *
 * Copyright (C) 2009-2010
 *     Geoffrey Biggs
 *     RT-Synthesis Research Group
 *     Intelligent Systems Research Institute,
 *     National Institute of Advanced Industrial Science and Technology (AIST),
 *     Japan
 *     All rights reserved.
 * Licensed under the Eclipse Public License -v 1.0 (EPL)
 * http://www.opensource.org/licenses/eclipse-1.0.txt
 *
 * Component service ports IDL.
 */


#ifndef SERVICES_IDL__
#define SERVICES_IDL__

#include "ExtendedDataTypes.idl"
#include "InterfaceDataTypes.idl"

module RTC
{

interface <INTERFACE>
{
    <RESULT_TYPE> <METHOD>();
};

}; // module RTC

#endif // SERVICES_IDL__

